name: Generate Playlist

on:
  schedule:
    # 6am UTC monday
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: get access token
      run: echo "SPOTIFY_ACCESS_TOKEN=$(scripts/get-access-token.sh)" >> $GITHUB_ENV
    - name: generate playlist
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Generate weekly playlist"
        file_pattern: playlists/*.md
        commit_author: Github Actions <actions@github.com>
